apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-manager
  name: cert-manager
  namespace: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
    metadata:
      labels:
        app: cert-manager
  template:
    spec:
      containers:
        - image: some/repo/gateway:latest
          name: gateway
          env:
            - name: SENTRY_KEY
              value: "1234a"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SOMEENV
              value: helloworld
