apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: pnorth-test-cluster
  namespace: mlp-pnorth
spec:
  entityOperator:
    topicOperator:
      image: kafka-image-1
    userOperator:
      image: kafka-image-2
  kafka:
    image: kafka-image-3
    replicas: 3
    config:
      inter.broker.protocol.version: "2.8"
      log.message.format.version: "2.8"
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    resources:
      requests:
        memory: 3Gi
        cpu: 100m
        ephemeral-storage: 16Mi
      limits:
        memory: 16Gi
        cpu: 300m
        ephemeral-storage: 128Mi
    listeners:
      - name: plain
        type: internal
        port: 9092
        tls: false
      - name: tls
        type: internal
        port: 9093
        tls: true
    storage:
      type: jbod
      volumes:
        - type: persistent-claim
          class: mlp-standard
          deleteClaim: true
          id: 0
          size: 20Gi
    version: 2.8.0
  zookeeper:
    image: kafka-image-4
    replicas: 3
    resources:
      requests:
        memory: .25Gi
        cpu: 100m
        ephemeral-storage: 24Mi
      limits:
        memory: 1.25Gi
        cpu: 500m
        ephemeral-storage: 124Mi
    storage:
      class: mlp-standard
      type: persistent-claim
      deleteClaim: true
      size: 64Gi
  kafkaExporter:
    image: kafka-image-5
