apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
spec:
  replicas: 1
  selector:
    metadata:
      labels:
        app: cert-manager
    matchLabels:
      app: cert-manager
  template:
    spec:
      containers:
        - name: gateway
          image: some/repo/gateway:latest
          env:
            - name: SOMEENV
              value: helloworld
